services:
  retriever:
    build:
      context: .
      target: final
    ports:
      - 8080:8080    
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 12s
      retries: 8
      start_period: 2s
      timeout: 12s
    environment:
      PORT: "8080"
      CONFIG_PATH: /config/testconfig.yaml
      SECRET_PATH: /secrets/secret.txt
    volumes:
      - ./test/:/config/
      - ./dev/:/secrets/
