apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "routriever.fullname" . }}-config
  labels:
    {{- include "routriever.labels" . | nindent 4 }}
data:
  config.yaml: |-
    updateInterval: {{ .Values.gpsServices.updateInterval }}
    {{- with .Values.routes }}
    routes:
      {{- toYaml . | nindent 6 }}
    {{- end }}