apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "routriever.fullname" . }}-config
  labels:
    {{- include "routriever.labels" . | nindent 4 }}
data:
  config.yaml: |-
    updateInterval: {{ .Values.gpsServices.updateInterval }}
    routes:
      {{- range .Values.routes }}
      - name: "{{ .name }}"
        start:
          latitude: {{ .start.latitude }}
          longitude: {{ .start.longitude }}
        end:
          latitude: {{ .end.latitude }}
          longitude: {{ .end.longitude }}
      {{- end }}