apiVersion: v1
kind: Secret
metadata:
  name: {{ include "routriever.fullname" . }}-secret
  labels:
    {{- include "routriever.labels" . | nindent 4 }}
data:
  tomTomApiKey: {{ .Values.gpsServices.tomTomService.apiKey | b64enc }}


# Some common paths used for mounting secrets include:

# - `/etc/secrets` or `/opt/secrets`: For storing application-specific secrets
# - `/run/secrets`: For storing ephemeral secrets that should not persist across container restarts
# - `/var/run/secrets`: Another common location for storing ephemeral secrets