apiVersion: v1
kind: Secret
metadata:
  name: {{ include "routriever.fullname" . }}-secret
  labels:
    {{- include "routriever.labels" . | nindent 4 }}
data:
  tomTomApiKey: {{ .Values.gpsServices.tomTomService.apiKey | b64enc }}
