{{- if .Values.serviceAccount.create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "routriever.fullname" . }}
  labels:
    {{- include "routriever.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "routriever.labels" . | nindent 4 }}
  endpoints:
  - port: {{ .Values.service.portName }}
    interval: {{ .Values.serviceMonitor.interval }}
{{- end }}