{{- if .Values.serviceAccount.create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:{{ include "routriever.fullname" . }}
  labels:
    {{- include "routriever.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "routriever.selectorLabels" . | nindent 4 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
{{- end }}